repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ^dotSCAD/
      - id: end-of-file-fixer
        exclude: ^dotSCAD/
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [-w]
        exclude: |
          (?x)^(
            dotSCAD/|
            fonts.*/|
            bmps/|
            stls/|
            .*\.scad|
            .*\.bdf|
            .*\.brd|
            .*\.sch|
            .*\.png|
            .*\.xcf|
            uv\.lock
          )

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.21.0"
    hooks:
      - id: pyproject-fmt
